spring:
  application:
    name: Atody
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/e-farm
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml